"""Planning orchestration.

Ties the deterministic analysis layer to a provider:

    analyze_repo -> PlanningRequest -> provider.generate_plan -> ImplementationPlan

Generation metadata is stamped by codegraft after parsing (never by the model),
so provenance is trustworthy regardless of what the model returns.

The Phase 1 stub plan is kept behind `build_stub_plan` so `codegraft plan --stub`
still works offline (handy for demos without an API key).
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from codegraft.config import Config
from codegraft.errors import ProviderError
from codegraft.models.plan import (
    AgentPrompt,
    Confidence,
    GenerationMetadata,
    ImplementationPlan,
    PlannedFileChange,
    PlanPhase,
    ReviewedFile,
    RiskItem,
    RiskSeverity,
    TestItem,
)
from codegraft.providers.base import PlanningRequest, PlanProvider
from codegraft.repo.analyze import analyze_repo


def get_provider(config: Config) -> PlanProvider:
    """Construct the provider named in config. Imports adapters lazily."""

    name = config.provider.name.lower()
    if name == "anthropic":
        from codegraft.providers.anthropic_provider import AnthropicProvider

        return AnthropicProvider(config)
    if name == "openai":
        from codegraft.providers.openai_provider import OpenAIProvider

        return OpenAIProvider(config)
    raise ProviderError(f"unknown provider: {config.provider.name!r}")


def generate_plan(
    request: str,
    repo: Path,
    config: Config,
    *,
    subdir: str | None = None,
    provider: PlanProvider | None = None,
) -> ImplementationPlan:
    """Run the full pipeline and return a validated, metadata-stamped plan."""

    analysis = analyze_repo(request, repo, config, subdir=subdir)
    provider = provider or get_provider(config)

    planning_request = PlanningRequest(
        feature_request=request,
        repo_root=analysis.scan.root,
        summary=analysis.summary,
        ranked=analysis.ranked,
        snippets=analysis.snippets,
    )
    plan = provider.generate_plan(planning_request)

    # Stamp provenance ourselves — the model must not author this.
    tokens = analysis.token_estimate()
    plan.metadata = GenerationMetadata(
        provider=config.provider.name,
        model=config.provider.model,
        repo_root=analysis.scan.root,
        timestamp=datetime.now().isoformat(timespec="seconds"),
        ranked_file_count=len(analysis.ranked),
        reviewed_file_count=len(analysis.snippets),
        context_tokens=tokens.bundle_tokens,
        tokens_saved=tokens.saved_tokens,
    )
    return plan


def _title_case(request: str) -> str:
    """Upper-case the first character only.

    ``str.capitalize()`` also *lower-cases the remainder*, which mangles the
    acronyms that show up in real requests ("Add RBAC to admin routes" became
    "Add rbac to admin routes").
    """

    text = request.strip()
    return text[:1].upper() + text[1:]


def build_stub_plan(request: str, repo_root: Path, config: Config) -> ImplementationPlan:
    """Return a representative, hand-built plan (no model call).

    Offline placeholder used by `codegraft plan --stub`. It does not analyze the
    repository; every section is marked [STUB].
    """

    return ImplementationPlan(
        title=_title_case(request) or "Implementation Plan",
        feature_summary=(
            f'[STUB] This is a placeholder plan for the request: "{request.strip()}". '
            "Run without --stub (with an API key set) for a real, evidence-backed plan."
        ),
        assumptions=[
            "This output was generated by the offline stub, not an LLM.",
            "No repository files were actually read to produce this plan.",
        ],
        open_questions=["Which provider and model should generate the real plan?"],
        relevant_architecture=(
            "[STUB] Run a real plan to get an architecture summary from your repo."
        ),
        files_reviewed=[
            ReviewedFile(
                path="(none — stub)",
                why_it_matters="Placeholder; a real run lists files from the evidence bundle.",
                confidence=Confidence.low,
            )
        ],
        files_likely_to_modify=[
            PlannedFileChange(
                path="(unknown — stub)",
                expected_change="Determined by a real planning run.",
                reason="Stub plan has no repository evidence.",
            )
        ],
        implementation_phases=[
            PlanPhase(
                name="Phase A: run a real plan",
                goal="Generate an evidence-backed plan from the actual repository.",
                likely_files=[],
                tasks=["Set ANTHROPIC_API_KEY", "Run `codegraft plan` without --stub"],
                acceptance_criteria=["A real plan is generated from repo evidence."],
                validation=["codegraft plan \"<your request>\" --repo ."],
            )
        ],
        risks=[
            RiskItem(
                description="Treating this stub output as a real plan.",
                severity=RiskSeverity.high,
                mitigation="Look for the [STUB] markers; run without --stub.",
            )
        ],
        test_plan=[
            TestItem(
                kind="unit",
                description="Renderer always emits every required section.",
                target="tests/test_renderer.py",
            )
        ],
        claude_code_prompts=[
            AgentPrompt(
                phase_name="Phase A: run a real plan",
                prompt="Set an API key and run codegraft plan without --stub.",
            )
        ],
        definition_of_done=["codegraft plan produces a real, evidence-backed plan."],
        metadata=GenerationMetadata(
            provider="stub",
            model="none",
            repo_root=str(repo_root.resolve()),
            timestamp=datetime.now().isoformat(timespec="seconds"),
        ),
    )
